repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
      - id: pyupgrade
        args:
          - "--py37-plus"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: '/mibs'
  - repo: https://github.com/python/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: '/mibs'
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-docstrings,
          flake8-builtins,
          flake8-comprehensions,
          flake8-print,
          flake8-eradicate,
          flake8-requirements-absolute-imports,
        ]
        args: [
          --project-base-module=cloudshell.template,
          "--known-modules=cloudshell-shell-core:[cloudshell.shell.core]"
        ]
        exclude: '/mibs'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        additional_dependencies: [types-attrs]
        exclude: ^tests/
