language: python
jobs:
  include:
    - if: branch = master
      python: 2.7
      env: TOXENV=py27-master
      after_success: codecov
    - if: branch = master
      python: 3.7
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master
      python: 2.7
      env: TOXENV=py27-dev
      after_success: codecov
    - if: branch != master
      python: 3.7
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
      python: 3.7
    - env: TOXENV=pre-commit
      python: 3.7
    - stage: Deploy to Test PyPI release
      python: 3.7
      install: skip
      script: sed -i -E "s/^([0-9]+\.[0-9]+\.[0-9]+)$/\1.$TRAVIS_BUILD_NUMBER/" version.txt
      deploy:
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: quali
        password:
          secure: neiCeyxYGTOmLeUvMnc/A1qCgscDvDyLDD4kb3PHEEywjsMhGjrK4HuWCg8Q1SKCJLbeuKDfEjKMy2tl3vhDGV529UU8G3FBCEgFglsrq0ZwuWYl9imXiuDCfBMdTk4eBuPsmp9FAKqXykwYMkfCrkFX30TolI1ATciDUaS075GaMT6BQTjnfCLwkm5XNZ6zO9mMbu4CBvK3bChbe46H7d8m01xcP4HvKIYYXUKD5/6hg1jTGo25EofikwptoYksdezhhT1ygg8qYe9/dbNo9kJ0Z+bOu3sGnjw8n0HHznhjQ8NgTSgraCaTolcWFdc3Ui1B42yRvGZsJ8jb81EzMkZZsVWwUFNx80pdUzlEX3VExYB7IfuhI3iAB3h745320rBYTGLqVyh/2GBsABYLmqAeqgS+me+y2QH+VHZ4uTQmOz5FCs6YhlDEXiQ66UVNBUBTwjVYU+jCvKvnuxxAOv40Ij0AkHEN09gx19xwFB3COvbpm/qEcnORV6VTJA22OHeZYxVy1zdb/lPioC107IeFdokdUt2yqlNyPMvtem+9GTyKaRudfV16g29t6uGFES1vOu1PFoER95hOBzoEhsg3tu6AdVPa3a0jEWZfr6IGeQkDRUfFo/W5hcuxmz5N+5j4AQ8RNCQO+Mc5QnJK6KanDog4mAh6nyGzhM90Yck=
        on:
          all_branches: true  # fixme
    - stage: Create GitHub release
      python: 3.7
      env: TOXENV=build
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          secure: oVZ0sWa7p9w0sMlxVWLCOkCkcwEBb7uMHz4lYtBrKyAaisHi6Cbz3muQHHmv+bZ116KJea+UcrN/gaCIs5Mchfb6WjLKJn7fFaWxdsX2RncfNR8QJ14mXpJwJAPV9IEnGK01CboSt5kT5koI8oaISprt6sFTnIWliCsBESniJZH9X3rC62cELZOodpGUm7tSd6+cjKwNB75Hgxv5nQREgi8W6GAo7EKga4pTqfD08tvYPGfp5gkZbvUTt04iIfV48nBjBe6O7e1+3IHycAOpPTOQPNRntUvRxlWGo5BI7pmaVlZfZ38LR2aNRw8I32PeugIM6Hhuq5FtecnzpkTBoUpz9gEnrdvPosW6kkOHUMaaRSEpzam6VCdS0KCwzFcxqalQI01cn+Xl1yeSASeLvP9UbAykZ3bsA4FqbdLbkzWnVetbU0CDfMz8tamxOdikExdtrfCl/6hxM75wv+tjLL7UYfaEXdt6Dno0xVebH4om6JuObVMpVz8+2DJzKYRFt94ZL/7HAVAAh8n7xMwqoH+9CpggGk2Q8wp3pq0SM/zV9rut7tgV7BxOoLCr5WZdr8I3lwMc+vqZrNZ80RSez6m6wQu/krpFacIFNsAQ5A09Mi8dcpVwn4y30xqcPVFIV1L/XWkiJVRt+rUX1P90QFZDpbrUl031ISjVbyfvXIg=
        file_glob: true
        file: dist/*.zip
        on:
          all_branches: true

install:
  - pip install tox
  - pip install codecov

script: tox

stages:
  - Test
  - Deploy to Test PyPI release
  - Create GitHub release
