language: python
python: 3.7
jobs:
  include:
    - if: branch = master
      python: 2.7
      env: TOXENV=py27-master
      after_success: codecov
    - if: branch = master
      env: TOXENV=py37-master
      after_success: codecov
    - if: branch != master
      python: 2.7
      env: TOXENV=py27-dev
      after_success: codecov
    - if: branch != master
      env: TOXENV=py37-dev
      after_success: codecov
    - env: TOXENV=build
    - env: TOXENV=pre-commit
    - stage: Deploy to Test PyPI release
      env: TOXENV=build
      before_script: sed -i -E "s/^([0-9]+\.[0-9]+\.[0-9]+)$/\1.$TRAVIS_BUILD_NUMBER/" version.txt
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/
        user: "__token__"
        password:
          # `travis encrypt token`
          secure: vSk6/P3sklyabNsEa9xGzL2th7EwtisAJMy+uC9eBqbfCfk7fspUZHNwvpDjI/r+f67Us3svsszR35xIuV2LfO6JqexRVCQzWydwPsAC42g1IgGftkihrxPji8fujxc0rirowUg4PqJdWIQkFvUbYSJWiLt2A2hjsBBxYt5sqa+JHK/HFkd2TLMlWS6zwh3/eFVagT1ju84oVfcXHKD5gPkS/jb/FjfKvD5GOIQbp0OrXomtsYQt+CJfOmN01AYNSmeTPwkHzrJ14AC3oxak6SwPBapoHR/0kJ79FxMt4C73xWEjaKcufD1rCqYIabZN3OHNEwInX6xbIUkiXUOLoGc6aAIeOQvaugy2bd/VSvNtAAmIFFRtp7FS/7/W3jL5Zm/Umn61OxAY7sXqADf8Evtq6Q7WugsxUiD6oKn7aDxzz53Pc91fxnP0mEDtbhlSlcGI3E0n3Qv+NVPrpx2OAz3Oa3hWjofFapP6oddsXdrBmJHVJMct2FvWcxel1j0dfvMIb50MOjQGc1mQA9mfh/1xb6T4RjicJhf27agxCimktGGKaqSUq4A1w1hXRQjENL0FSZUOfcShCc1q1szcPxeLlnY5hUkY3utf4dY5FM/LOpPKDDwrLKF6X7I2dB2nGh3UwOp0EnXQ+23EZYsAJYrVsoyfbN/utGh5pvn65rU=
        on:
          branch: dev
    - stage: Deploy to PyPI release
      env: TOXENV=build
      deploy:
        distributions: skip
        skip_cleanup: true
        provider: pypi
        server: https://test.pypi.org/legacy/  # fixme remove the line
        user: "__token__"
        password:
          # `travis encrypt token`
          secure: vSk6/P3sklyabNsEa9xGzL2th7EwtisAJMy+uC9eBqbfCfk7fspUZHNwvpDjI/r+f67Us3svsszR35xIuV2LfO6JqexRVCQzWydwPsAC42g1IgGftkihrxPji8fujxc0rirowUg4PqJdWIQkFvUbYSJWiLt2A2hjsBBxYt5sqa+JHK/HFkd2TLMlWS6zwh3/eFVagT1ju84oVfcXHKD5gPkS/jb/FjfKvD5GOIQbp0OrXomtsYQt+CJfOmN01AYNSmeTPwkHzrJ14AC3oxak6SwPBapoHR/0kJ79FxMt4C73xWEjaKcufD1rCqYIabZN3OHNEwInX6xbIUkiXUOLoGc6aAIeOQvaugy2bd/VSvNtAAmIFFRtp7FS/7/W3jL5Zm/Umn61OxAY7sXqADf8Evtq6Q7WugsxUiD6oKn7aDxzz53Pc91fxnP0mEDtbhlSlcGI3E0n3Qv+NVPrpx2OAz3Oa3hWjofFapP6oddsXdrBmJHVJMct2FvWcxel1j0dfvMIb50MOjQGc1mQA9mfh/1xb6T4RjicJhf27agxCimktGGKaqSUq4A1w1hXRQjENL0FSZUOfcShCc1q1szcPxeLlnY5hUkY3utf4dY5FM/LOpPKDDwrLKF6X7I2dB2nGh3UwOp0EnXQ+23EZYsAJYrVsoyfbN/utGh5pvn65rU=
        on:
          tags: true
    - stage: Create GitHub release
      env: TOXENV=build
      before_deploy:
        - export AUTHOR_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
        - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
        - export GIT_TAG="$(cat version.txt | tr -d ' \t\n\r')"
        - git config --local user.name $AUTHOR_NAME
        - git config --local user.email $AUTHOR_EMAIL
        - git tag $GIT_TAG
      deploy:
        provider: releases
        skip_cleanup: true
        draft: true
        api_key:
          # `travis encrypt token`
          secure: oVZ0sWa7p9w0sMlxVWLCOkCkcwEBb7uMHz4lYtBrKyAaisHi6Cbz3muQHHmv+bZ116KJea+UcrN/gaCIs5Mchfb6WjLKJn7fFaWxdsX2RncfNR8QJ14mXpJwJAPV9IEnGK01CboSt5kT5koI8oaISprt6sFTnIWliCsBESniJZH9X3rC62cELZOodpGUm7tSd6+cjKwNB75Hgxv5nQREgi8W6GAo7EKga4pTqfD08tvYPGfp5gkZbvUTt04iIfV48nBjBe6O7e1+3IHycAOpPTOQPNRntUvRxlWGo5BI7pmaVlZfZ38LR2aNRw8I32PeugIM6Hhuq5FtecnzpkTBoUpz9gEnrdvPosW6kkOHUMaaRSEpzam6VCdS0KCwzFcxqalQI01cn+Xl1yeSASeLvP9UbAykZ3bsA4FqbdLbkzWnVetbU0CDfMz8tamxOdikExdtrfCl/6hxM75wv+tjLL7UYfaEXdt6Dno0xVebH4om6JuObVMpVz8+2DJzKYRFt94ZL/7HAVAAh8n7xMwqoH+9CpggGk2Q8wp3pq0SM/zV9rut7tgV7BxOoLCr5WZdr8I3lwMc+vqZrNZ80RSez6m6wQu/krpFacIFNsAQ5A09Mi8dcpVwn4y30xqcPVFIV1L/XWkiJVRt+rUX1P90QFZDpbrUl031ISjVbyfvXIg=
        file_glob: true
        file: dist/*
        name: cloudshell-template $GIT_TAG  # fixme set package name
        target_commitish: master
        on:
          branch: master
    - stage: Check version
      language: bash
      install:
        - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git checkout -qf $TRAVIS_PULL_REQUEST_BRANCH
      script: "! git diff --exit-code --quiet origin/master version.txt"

install:
  - pip install tox
  - pip install codecov

script: tox

stages:
  - name: Check version
    if: branch = master AND type = pull_request
  - name: Test
  - name: Deploy to Test PyPI release
    if: branch = dev AND type != pull_request
  - name: Create GitHub release
    if: branch = master AND type != pull_request
  - name: Deploy to PyPI release
    if: tag IS present
